config/routes.rb
InfoMoto::Application.routes.draw do
  get "home/dashboard"

  get "home/index"

  devise_for :users

  resources :rides

  resources :bikes

  resources :users

  root :to => 'home#index'

end

app/models/bike.rb
class Bike < ActiveRecord::Base
	#attr_accessible :make, :model, :year
	belongs_to :user
	has_many :rides
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  #switch to CanCan in the future
  before_filter :authenticate_user!
  
  # GET /bikes
  # GET /bikes.json
  def index
    @bikes = current_user.bikes

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bikes }
    end
  end

  # GET /bikes/1
  # GET /bikes/1.json
  def show
    @bike = Bike.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bike }
    end
  end

  # GET /bikes/new
  # GET /bikes/new.json
  def new
    @bike = Bike.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bike }
    end
  end

  # GET /bikes/1/edit
  def edit
    @bike = Bike.find(params[:id])
  end

  # POST /bikes
  # POST /bikes.json
  def create
    @bike = Bike.new(params[:bike])
    @bike.user = current_user
    
    respond_to do |format|
      if @bike.save
        format.html { redirect_to @bike, notice: 'Bike was successfully created.' }
        format.json { render json: @bike, status: :created, location: @bike }
      else
        format.html { render action: "new" }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bikes/1
  # PUT /bikes/1.json
  def update
    @bike = Bike.find(params[:id])

    respond_to do |format|
      if @bike.update_attributes(params[:bike])
        format.html { redirect_to @bike, notice: 'Bike was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1
  # DELETE /bikes/1.json
  def destroy
    @bike = Bike.find(params[:id])
    @bike.destroy

    respond_to do |format|
      format.html { redirect_to bikes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/bikes/_form.html.erb
<%= form_for(@bike) do |f| %>
  <% if @bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bike.errors.count, "error") %> prohibited this bike from being saved:</h2>

      <ul>
      <% @bike.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :mileage %><br />
    <%= f.number_field :mileage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bikes/edit.html.erb
<h1>Editing bike</h1>

<%= render 'form' %>

<%= link_to 'Show', @bike %> |
<%= link_to 'Back', bikes_path %>

app/views/bikes/index.html.haml
%h1 Your Bikes
%center
  %table
    %thead
      %tr
        %th Make
        %th Model
        %th Year
        %th Mileage
        %th
        %th
        %th
    %tbody
      - @bikes.each do |bike|
        %tr
          %td= bike.make
          %td= bike.model
          %td= bike.year
          %td= bike.mileage
          %td= link_to 'Show', bike
          %td= link_to 'Edit', edit_bike_path(bike)
          %td= link_to 'Destroy', bike, confirm: 'Are you sure?', method: :delete
%br
= link_to 'New Bike', new_bike_path

app/views/bikes/new.html.erb
<h1>New bike</h1>

<%= render 'form' %>

<%= link_to 'Back', bikes_path %>

app/views/bikes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Make:</b>
  <%= @bike.make %>
</p>

<p>
  <b>Model:</b>
  <%= @bike.model %>
</p>

<p>
  <b>Year:</b>
  <%= @bike.year %>
</p>

<p>
  <b>Mileage:</b>
  <%= @bike.mileage %>
</p>


<%= link_to 'Edit', edit_bike_path(@bike) %> |
<%= link_to 'Back', bikes_path %>