config/routes.rb
InfoMoto::Application.routes.draw do
  get "home/dashboard"

  get "home/index"

  devise_for :users

  resources :rides

  resources :bikes

  resources :users

  root :to => 'home#index'

end

app/models/ride.rb
class Ride < ActiveRecord::Base
	belongs_to :bike
	belongs_to :user
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  #switch to CanCan in the future
  before_filter :authenticate_user!
  
  # GET /rides
  # GET /rides.json
  def index
    @rides = current_user.rides

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rides }
    end
  end

  # GET /rides/1
  # GET /rides/1.json
  def show
    @ride = Ride.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ride }
    end
  end

  # GET /rides/new
  # GET /rides/new.json
  def new
    @ride = Ride.new
    @user_bikes = current_user.bikes
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ride }
    end
  end

  # GET /rides/1/edit
  def edit
    @ride = Ride.find(params[:id])
    @user_bikes = current_user.bikes
  end

  # POST /rides
  # POST /rides.json
  def create
    @ride = Ride.new(params[:ride])
    @ride.user = current_user
    
    respond_to do |format|
      if @ride.save
        format.html { redirect_to @ride, notice: 'Ride was successfully created.' }
        format.json { render json: @ride, status: :created, location: @ride }
      else
        format.html { render action: "new" }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rides/1
  # PUT /rides/1.json
  def update
    @ride = Ride.find(params[:id])

    respond_to do |format|
      if @ride.update_attributes(params[:ride])
        format.html { redirect_to @ride, notice: 'Ride was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1
  # DELETE /rides/1.json
  def destroy
    @ride = Ride.find(params[:id])
    @ride.destroy

    respond_to do |format|
      format.html { redirect_to rides_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/rides/_form.html.erb
<%= form_for(@ride) do |f| %>
  <% if @ride.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ride.errors.count, "error") %> prohibited this ride from being saved:</h2>

      <ul>
      <% @ride.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bike %><br />
    <%= f.select(:bike_id, @user_bikes.map {|b| [ b.make + ' ' + b.model + ' ' + b.year.to_s, b.id ] }) %>
	  <%= link_to 'New Bike', new_bike_path %>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.datetime_select :end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rides/edit.html.erb
<h1>Editing ride</h1>

<%= render 'form' %>

<%= link_to 'Show', @ride %> |
<%= link_to 'Back', rides_path %>

app/views/rides/index.html.erb
<h1>Listing rides</h1>
<center>
  <table>
    <tr>
      <th>Name</th>
      <th>Bike</th>
      <th>Start</th>
      <th>End</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @rides.each do |ride| %>
    <tr>
      <td><%= ride.name %></td>
      <td><%= (ride.bike.make + ' ' + ride.bike.model + ' ' + ride.bike.year.to_s) if ride.bike %></td>
      <td><%= ride.start %></td>
      <td><%= ride.end %></td>
      <td><%= link_to 'Upload Data', '#' %></td>
      <td><%= link_to 'Show', ride %></td>
      <td><%= link_to 'Edit', edit_ride_path(ride) %></td>
      <td><%= link_to 'Destroy', ride, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>
</center>
<br />

<%= link_to 'New Ride', new_ride_path %>

app/views/rides/new.html.erb
<h1>New ride</h1>

<%= render 'form' %>

<%= link_to 'Back', rides_path %>

app/views/rides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ride.name %>
</p>
<p>
  <b>Bike:</b>
  <%= (@ride.bike.make + ' ' + @ride.bike.model + ' ' + @ride.bike.year.to_s) if @ride.bike %>
</p>
<p>
  <b>Start:</b>
  <%= @ride.start %>
</p>

<p>
  <b>End:</b>
  <%= @ride.end %>
</p>


<%= link_to 'Edit', edit_ride_path(@ride) %> |
<%= link_to 'Back', rides_path %>